// Inicialización de categorías en localStorage
categorias = {
  101: {
    codigo: "101",
    nombre: "Arquitectura",
    descripcion: "libros de arquitectura",
    imagen: "img/arquitectura.png",
  },
  102: {
    codigo: "102",
    nombre: "Biblias",
    descripcion: "Biblias",
    imagen: "img/biblia.png",
  },
  103: {
    codigo: "103",
    nombre: "Lit. Colombiana",
    descripcion: "Libros de autores colombianos",
    imagen: "img/colombia.png",
  },
  104: {
    codigo: "104",
    nombre: "Espiritualidad y Autoayuda",
    descripcion: "libros de espiritualidad y autoayuda",
    imagen: "img/espiritualidad_autoayuda.png",
  },
  105: {
    codigo: "105",
    nombre: "Filosofía",
    descripcion: "libros de filosofía",
    imagen: "img/filosofia.png",
  },
  106: {
    codigo: "106",
    nombre: "Informatica y programación",
    descripcion: "libros de informatica y programación",
    imagen: "img/informatica.png",
  },
  107: {
    codigo: "107",
    nombre: "Lit. Latinoamericana",
    descripcion: "libros de autores latinoamericanos",
    imagen: "img/latinoamericana.png",
  },
  108: {
    codigo: "108",
    nombre: "Mangas y Comics",
    descripcion: "libros de mangas, comics y novelas graficas",
    imagen: "img/manga.png",
  },
  109: {
    codigo: "109",
    nombre: "Superación Personal",
    descripcion: "libros de superación personal",
    imagen: "img/superacion_personal.png",
  },
  110: {
    codigo: "110",
    nombre: "Universitarios",
    descripcion: "libros tecnicos universitarios",
    imagen: "img/universitarios.png",
  },
};

localStorage.setItem("categorias", JSON.stringify(categorias));

// Inicialización de banners en el localStorage
banners = {
  101: {
    codigo: "101",
    titulo: "Cien años de soledad",
    subtitulo: "",
    descripcion:
      "Probablemente la novela más famosa de la literatura colombiana y una de las más importantes de la literatura universal. Narra la historia de la familia Buendía a lo largo de siete generaciones en el mítico pueblo de Macondo. Obra cumbre del realismo mágico.",
    imagen: "img/cien_anos_soledad.png",
  },
  102: {
    codigo: "102",
    titulo: "Rayuela",
    subtitulo: "",
    descripcion:
      "Una de las novelas más influyentes y experimentales de la literatura latinoamericana. Es célebre porque se puede leer de manera lineal o siguiendo un orden alternativo de capítulos. Narra la historia de Horacio Oliveira y su círculo de bohemios en París y Buenos Aires.",
    imagen: "img/rayuela.png",
  },
  103: {
    codigo: "103",
    titulo: "Meditaciones",
    subtitulo: "",
    descripcion:
      "Obra cumbre del estoicismo. Son pensamientos personales del emperador romano sobre cómo vivir con virtud, serenidad y aceptación frente a la adversidad. Un libro atemporal sobre ética práctica y equilibrio emocional.",
    imagen: "img/meditaciones.png",
  },
};

localStorage.setItem("banners", JSON.stringify(banners));

// Inicialización de productos en el localStorage
const productos = {
  1011: {
    codigo: "1011",
    titulo: "Pedro Paramo",
    autor: "Juan Rulfo",
    editorial: "Planeta",
    isbn: "000-000-0000-00-0",
    categoria: "107",
    imagen: "img/pedro_paramo.png",
    precio: 15000,
    sinopsis:
      "Una novela fundamental del realismo mágico que narra la historia de Juan Preciado, quien llega al pueblo de Comala en busca de su padre, Pedro Páramo. A través de una narrativa onírica y fragmentada, Rulfo explora temas de muerte, soledad y el poder de los recuerdos.",
    calificacion: 4.5,
  },
  1012: {
    codigo: "1012",
    titulo: "El mito de sísifo",
    autor: "Albert Camus",
    editorial: "Norma",
    isbn: "000-000-0000-00-0",
    categoria: "105",
    imagen: "img/mito_sisifo.png",
    precio: 52000,
    sinopsis:
      "Un ensayo filosófico donde Camus explora el absurdo de la vida y la búsqueda de significado. Utiliza el mito griego de Sísifo, condenado a empujar una roca cuesta arriba solo para verla rodar hacia abajo, como metáfora de la lucha humana por encontrar sentido en un mundo indiferente.",
    calificacion: 4.7,
  },
  1013: {
    codigo: "1013",
    titulo: "Delirio",
    autor: "Laura Restrepo",
    editorial: "Alfaguara",
    isbn: "000-000-0000-00-0",
    categoria: "103",
    imagen: "img/delirio.png",
    precio: 49000,
    sinopsis:
      "Una novela que narra la historia de Agustina, una mujer que sufre un colapso mental y es internada en un hospital psiquiátrico. A través de sus delirios, se revela la historia de su familia y el contexto social y político de Colombia en los años 80. Una obra que mezcla realidad y ficción con maestría.",
    calificacion: 4.6,
  },
  1014: {
    codigo: "1014",
    titulo: "El amor en los tiempos del cólera",
    autor: "Gabriel García Márquez",
    editorial: "Random House",
    isbn: "000-000-0000-00-0",
    categoria: "103",
    imagen: "img/amor_tiempos_colera.png",
    precio: 60000,
    sinopsis:
      "Una novela que narra la historia de amor entre Florentino Ariza y Fermina Daza, quienes se reencuentran después de más de 50 años. García Márquez explora el amor en sus diversas formas y etapas, desde la pasión juvenil hasta el amor maduro, en un contexto de realismo mágico.",
    calificacion: 4.8,
  },
  1015: {
    codigo: "1015",
    titulo: "El túnel",
    autor: "Ernesto Sabato",
    editorial: "Sudamericana",
    isbn: "000-000-0000-00-0",
    categoria: "107",
    imagen: "img/tunel.png",
    precio: 45000,
    sinopsis:
      "Una novela psicológica que narra la obsesión de Juan Pablo Castel, un pintor que se enamora de María, una mujer casada. A través de su perspectiva distorsionada, Sabato explora temas de aislamiento, locura y la búsqueda de significado en un mundo caótico.",
    calificacion: 4.4,
  },
  1016: {
    codigo: "1016",
    titulo: "Cien años de soledad",
    autor: "Gabriel García Márquez",
    editorial: "Random House",
    isbn: "000-000-0000-00-0",
    categoria: "103",
    imagen: "img/cien_anos_soledad.png",
    precio: 70000,
    sinopsis:
      "Una de las obras más emblemáticas del realismo mágico, narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo. García Márquez entrelaza lo fantástico con lo cotidiano, explorando temas como la soledad, el poder y el destino.",
    calificacion: 5.0,
  },
  1017: {
    codigo: "1017",
    titulo: "Rayuela",
    autor: "Julio Cortázar",
    editorial: "Siglo XXI",
    isbn: "000-000-0000-00-0",
    categoria: "107",
    imagen: "img/rayuela.png",
    precio: 80000,
    sinopsis:
      "Una novela innovadora que permite múltiples lecturas y estructuras narrativas. Sigue la vida de Horacio Oliveira, un intelectual argentino en París, y su relación con La Maga. Cortázar juega con el tiempo y la realidad, creando una obra maestra de la literatura latinoamericana.",
    calificacion: 4.9,
  },
  1018: {
    codigo: "1018",
    titulo: "Meditaciones",
    autor: "Marco Aurelio",
    editorial: "Gredos",
    isbn: "000-000-0000-00-0",
    categoria: "105",
    imagen: "img/meditaciones.png",
    precio: 30000,
    sinopsis:
      "Una colección de pensamientos y reflexiones del emperador romano Marco Aurelio, escrita como un diario personal. En ella, Aurelio aborda temas de estoicismo, ética, autocontrol y la naturaleza efímera de la vida. Es una obra atemporal que ofrece sabiduría práctica para enfrentar las adversidades.",
    calificacion: 4.8,
  },
  1019: {
    codigo: "1019",
    titulo: "El principito",
    autor: "Antoine de Saint-Exupéry",
    editorial: "Salamandra",
    isbn: "000-000-0000-00-0",
    categoria: "104",
    imagen: "img/principito.png",
    precio: 25000,
    sinopsis:
      "Un cuento filosófico que narra la historia de un joven príncipe que viaja de planeta en planeta, aprendiendo lecciones sobre la vida, el amor y la amistad. A través de su mirada inocente, Saint-Exupéry invita a los lectores a reflexionar sobre la naturaleza humana y la importancia de ver más allá de lo superficial.",
    calificacion: 4.7,
  },
  1020: {
    codigo: "1020",
    titulo: "El arte de la guerra",
    autor: "Sun Tzu",
    editorial: "Alianza",
    isbn: "000-000-0000-00-0",
    categoria: "105",
    imagen: "img/arte_guerra.png",
    precio: 40000,
    sinopsis:
      "Un antiguo tratado chino sobre estrategia militar y filosofía. Aunque fue escrito para el contexto de la guerra, sus enseñanzas se aplican a muchos aspectos de la vida, como la toma de decisiones, la resolución de conflictos y la gestión de recursos. Es un texto fundamental en la literatura sobre liderazgo y estrategia.",
    calificacion: 4.6,
  },
  1021: {
    codigo: "1021",
    titulo: "El alquimista",
    autor: "Paulo Coelho",
    editorial: "Planeta",
    isbn: "000-000-0000-00-0",
    categoria: "104",
    imagen: "img/alquimista.png",
    precio: 35000,
    sinopsis:
      "Una novela que narra la historia de Santiago, un joven pastor andaluz que busca su leyenda personal y el significado de la vida. A través de su viaje, Coelho explora temas como el destino, los sueños y la búsqueda de la felicidad. Es una obra inspiradora que invita a los lectores a seguir sus propios sueños.",
    calificacion: 4.5,
  },
  1022: {
    codigo: "1022",
    titulo: "1984",
    autor: "George Orwell",
    editorial: "Debolsillo",
    isbn: "000-000-0000-00-0",
    categoria: "105",
    imagen: "img/1984.png",
    precio: 45000,
    sinopsis:
      "Una novela distópica que retrata un futuro totalitario donde el Partido controla todos los aspectos de la vida. A través de la historia de Winston Smith, Orwell explora temas como la vigilancia, la manipulación de la verdad y la lucha por la libertad individual. Es una obra que sigue siendo relevante en el contexto político actual.",
    calificacion: 4.9,
  },
  1023: {
    codigo: "1023",
    titulo: "Bogotá: Arquitectura y Urbanismo",
    autor: "GRicardo Daza Vargas",
    editorial: "Debolsillo",
    isbn: "000-000-0000-00-0",
    categoria: "105",
    imagen: "img/1984.png",
    precio: 45000,
    sinopsis:
      "Una novela distópica que retrata un futuro totalitario donde el Partido controla todos los aspectos de la vida. A través de la historia de Winston Smith, Orwell explora temas como la vigilancia, la manipulación de la verdad y la lucha por la libertad individual. Es una obra que sigue siendo relevante en el contexto político actual.",
    calificacion: 4.9,
  },
  1023: {
    codigo: "1023",
    titulo: "Bogotá: Arquitectura y Urbanismo",
    autor: "Ricardo Daza Vargas",
    editorial: "Universidad Nacional de Colombia",
    isbn: "978-958-719-485-4",
    categoria: "101",
    imagen: "img/bogota_arquitectura.png",
    precio: 65000,
    sinopsis:
      "Un recorrido visual y documental por la transformación urbana y arquitectónica de Bogotá, desde su fundación hasta el siglo XXI. Incluye fotografías históricas, planos y análisis de su evolución espacial y cultural.",
    calificacion: 4.6,
  },
  1024: {
    codigo: "1024",
    titulo: "Rogelio Salmona: El arquitecto, su vida y su obra",
    autor: "Sylvia Arango",
    editorial: "Editorial Universidad de los Andes",
    isbn: "978-958-774-031-0",
    categoria: "101",
    imagen: "img/rogelio_salmona.png",
    precio: 78000,
    sinopsis:
      "Biografía y estudio crítico de Rogelio Salmona, considerado el arquitecto colombiano más influyente. Analiza sus obras más emblemáticas como las Torres del Parque y la Biblioteca Virgilio Barco, y su legado urbano y cultural.",
    calificacion: 4.9,
  },
  1025: {
    codigo: "1025",
    titulo: "Arquitectura Contemporánea en Colombia",
    autor: "Daniel Bermúdez y varios autores",
    editorial: "Editorial Escala",
    isbn: "978-958-425-001-0",
    categoria: "101",
    imagen: "img/arquitectura_contemporanea.png",
    precio: 70000,
    sinopsis:
      "Compilación de las obras arquitectónicas más representativas de Colombia en las últimas décadas. Incluye proyectos de vivienda social, espacios públicos, bibliotecas y centros culturales que redefinen el paisaje urbano colombiano.",
    calificacion: 4.7,
  },
  1026: {
    codigo: "1026",
    titulo: "El poder del ahora",
    autor: "Eckhart Tolle",
    editorial: "Grijalbo",
    isbn: "978-958-888-889-3",
    categoria: "104",
    imagen: "img/poder_del_ahora.png",
    precio: 42000,
    sinopsis:
      "Una guía espiritual que invita a los lectores a vivir plenamente en el presente y liberarse de la ansiedad y el sufrimiento generado por el pasado y el futuro. Considerado un clásico contemporáneo de la espiritualidad.",
    calificacion: 4.9,
  },
  1027: {
    codigo: "1027",
    titulo: "Los cuatro acuerdos",
    autor: "Miguel Ruiz",
    editorial: "Urano",
    isbn: "978-958-861-395-2",
    categoria: "104",
    imagen: "img/cuatro_acuerdos.png",
    precio: 38000,
    sinopsis:
      "Un libro de sabiduría tolteca que propone cuatro principios para alcanzar la libertad personal y vivir una vida plena: ser impecable con las palabras, no tomarse nada personal, no hacer suposiciones y dar siempre lo mejor.",
    calificacion: 4.7,
  },
  1028: {
    codigo: "1028",
    titulo: "Más fuerte que la adversidad",
    autor: "Walter Riso",
    editorial: "Planeta",
    isbn: "978-958-428-882-6",
    categoria: "104",
    imagen: "img/mas_fuerte_adversidad.png",
    precio: 46000,
    sinopsis:
      "Una obra que ofrece herramientas psicológicas y espirituales para afrontar con valentía las crisis, pérdidas y dificultades cotidianas. Un llamado a la resiliencia y al fortalecimiento emocional en tiempos complejos.",
    calificacion: 4.8,
  },
  1029: {
    codigo: "1029",
    titulo: "Más Platón y menos Prozac",
    autor: "Lou Marinoff",
    editorial: "Ediciones B",
    isbn: "978-958-8659-01-1",
    categoria: "105",
    imagen: "img/mas_platon.png",
    precio: 48000,
    sinopsis:
      "Un libro que propone usar la filosofía clásica como herramienta para resolver problemas personales y cotidianos. Marinoff explora cómo pensadores como Platón, Aristóteles y Kant pueden ayudarte más que un ansiolítico.",
    calificacion: 4.7,
  },
  1030: {
    codigo: "1030",
    titulo: "Así habló Zaratustra",
    autor: "Friedrich Nietzsche",
    editorial: "Alianza Editorial",
    isbn: "978-958-846-671-8",
    categoria: "105",
    imagen: "img/zaratustra.png",
    precio: 52000,
    sinopsis:
      "Obra filosófica y literaria en la que Nietzsche desarrolla conceptos como el superhombre, el eterno retorno y la voluntad de poder. Es una obra fundamental para entender la filosofía moderna y contemporánea.",
    calificacion: 4.8,
  },
  1031: {
    codigo: "1031",
    titulo: "La república",
    autor: "Platón",
    editorial: "Gredos",
    isbn: "978-958-888-001-9",
    categoria: "105",
    imagen: "img/la_republica.png",
    precio: 50000,
    sinopsis:
      "Un diálogo clásico donde Platón explora la justicia, la organización ideal de la sociedad y el papel de los filósofos en la política. Una obra base del pensamiento filosófico occidental.",
    calificacion: 4.9,
  },
  1032: {
    codigo: "1032",
    titulo: "Clean Code",
    autor: "Robert C. Martin",
    editorial: "Prentice Hall",
    isbn: "978-0132350884",
    categoria: "106",
    imagen: "img/clean_code.png",
    precio: 78000,
    sinopsis:
      "Un libro esencial para desarrolladores que enseña cómo escribir código limpio, legible y fácil de mantener. Incluye buenas prácticas, ejemplos y principios de software profesional.",
    calificacion: 5.0,
  },
  1033: {
    codigo: "1033",
    titulo: "JavaScript: The Good Parts",
    autor: "Douglas Crockford",
    editorial: "O'Reilly Media",
    isbn: "978-0596517748",
    categoria: "106",
    imagen: "img/js_good_parts.png",
    precio: 64000,
    sinopsis:
      "Una guía concisa de las mejores y más efectivas características del lenguaje JavaScript, recomendada para desarrolladores que quieren escribir código eficiente y seguro.",
    calificacion: 4.7,
  },
  1034: {
    codigo: "1034",
    titulo: "Eloquent JavaScript",
    autor: "Marijn Haverbeke",
    editorial: "No Starch Press",
    isbn: "978-1593279509",
    categoria: "106",
    imagen: "img/eloquent_js.png",
    precio: 72000,
    sinopsis:
      "Una introducción moderna a JavaScript que combina teoría y práctica con ejercicios interactivos. Ideal para programadores principiantes y experimentados.",
    calificacion: 4.8,
  },
  1035: {
    codigo: "1035",
    titulo: "Python Crash Course",
    autor: "Eric Matthes",
    editorial: "No Starch Press",
    isbn: "978-1593279288",
    categoria: "106",
    imagen: "img/python_crash.png",
    precio: 75000,
    sinopsis:
      "Un curso intensivo de Python para principiantes que enseña los conceptos esenciales del lenguaje y cómo aplicarlos en proyectos prácticos como videojuegos y aplicaciones web.",
    calificacion: 4.9,
  },
  1036: {
    codigo: "1036",
    titulo: "Design Patterns",
    autor: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    editorial: "Addison-Wesley",
    isbn: "978-0201633610",
    categoria: "106",
    imagen: "img/design_patterns.png",
    precio: 82000,
    sinopsis:
      "Un clásico sobre patrones de diseño de software que ofrece soluciones probadas a problemas comunes en el desarrollo de aplicaciones. Es referencia obligada para programadores avanzados.",
    calificacion: 5.0,
  },
  1037: {
    codigo: "1037",
    titulo: "One Piece Vol. 1",
    autor: "Eiichiro Oda",
    editorial: "Planeta Cómic",
    isbn: "978-8491468881",
    categoria: "108",
    imagen: "img/one_piece_vol1.png",
    precio: 29000,
    sinopsis:
      "Primer volumen de la legendaria saga de piratas donde Monkey D. Luffy inicia su aventura para encontrar el One Piece y convertirse en el Rey de los Piratas.",
    calificacion: 5.0,
  },
  1038: {
    codigo: "1038",
    titulo: "Naruto Vol. 1",
    autor: "Masashi Kishimoto",
    editorial: "Panini Manga",
    isbn: "978-6075282777",
    categoria: "108",
    imagen: "img/naruto_vol1.png",
    precio: 28000,
    sinopsis:
      "Primer tomo de la historia de Naruto Uzumaki, un joven ninja con el sueño de ser el líder de su aldea mientras enfrenta peligros y descubre su propio valor.",
    calificacion: 4.9,
  },
  1039: {
    codigo: "1039",
    titulo: "Death Note Vol. 1",
    autor: "Tsugumi Ohba & Takeshi Obata",
    editorial: "Panini Manga",
    isbn: "978-6074291985",
    categoria: "108",
    imagen: "img/death_note_vol1.png",
    precio: 30000,
    sinopsis:
      "Light Yagami encuentra un cuaderno que permite matar a cualquiera cuyo nombre sea escrito en él. Así comienza una lucha moral y estratégica entre Light y el enigmático detective L.",
    calificacion: 4.9,
  },
  1040: {
    codigo: "1040",
    titulo: "Dragon Ball Vol. 1",
    autor: "Akira Toriyama",
    editorial: "Planeta Cómic",
    isbn: "978-8491468843",
    categoria: "108",
    imagen: "img/dragon_ball_vol1.png",
    precio: 27000,
    sinopsis:
      "Goku, un niño con fuerza sobrehumana, inicia su viaje para reunir las siete Esferas del Dragón. Una obra legendaria que marcó generaciones de lectores y fanáticos.",
    calificacion: 4.8,
  },
  1041: {
    codigo: "1041",
    titulo: "Attack on Titan Vol. 1",
    autor: "Hajime Isayama",
    editorial: "Norma Editorial",
    isbn: "978-8467918120",
    categoria: "108",
    imagen: "img/attack_on_titan_vol1.png",
    precio: 31000,
    sinopsis:
      "La humanidad vive tras murallas gigantes para protegerse de los titanes. Cuando un muro es destruido, Eren Jaeger jura venganza en esta brutal y emocionante saga.",
    calificacion: 4.9,
  },
  1042: {
    codigo: "1042",
    titulo: "Los secretos de la mente millonaria",
    autor: "T. Harv Eker",
    editorial: "Aguilar",
    isbn: "978-6071120845",
    categoria: "109",
    imagen: "img/mente_millonaria.png",
    precio: 42000,
    sinopsis:
      "Un libro que enseña cómo cambiar tu mentalidad financiera y adoptar hábitos de éxito económico. Eker explica las diferencias en la forma de pensar de las personas ricas y pobres.",
    calificacion: 4.8,
  },
  1043: {
    codigo: "1043",
    titulo: "Hábitos atómicos",
    autor: "James Clear",
    editorial: "Planeta",
    isbn: "978-6070758353",
    categoria: "109",
    imagen: "img/habitos_atomicos.png",
    precio: 46000,
    sinopsis:
      "James Clear revela un método comprobado para crear buenos hábitos, romper los malos y dominar las pequeñas conductas que llevan al éxito. Bestseller mundial de desarrollo personal.",
    calificacion: 4.9,
  },
  1044: {
    codigo: "1044",
    titulo: "El poder del ahora",
    autor: "Eckhart Tolle",
    editorial: "Grijalbo",
    isbn: "978-6073122113",
    categoria: "109",
    imagen: "img/poder_ahora.png",
    precio: 40000,
    sinopsis:
      "Un clásico de la espiritualidad moderna que enseña a vivir el presente y liberarse de la ansiedad del pasado y el futuro. Tolle propone técnicas de conciencia plena para alcanzar la paz interior.",
    calificacion: 4.8,
  },
  1045: {
    codigo: "1045",
    titulo: "Cálculo de una variable",
    autor: "James Stewart",
    editorial: "Cengage Learning",
    isbn: "978-6075261889",
    categoria: "110",
    imagen: "img/calculo_stewart.png",
    precio: 95000,
    sinopsis:
      "Un clásico indispensable para estudiantes universitarios de ingeniería y ciencias. Expone de forma clara los fundamentos del cálculo diferencial e integral de una variable.",
    calificacion: 4.9,
  },
  1046: {
    codigo: "1046",
    titulo: "Fundamentos de programación",
    autor: "Luis Joyanes Aguilar",
    editorial: "McGraw Hill",
    isbn: "978-6071514980",
    categoria: "110",
    imagen: "img/fundamentos_programacion.png",
    precio: 88000,
    sinopsis:
      "Texto fundamental para estudiantes de informática y sistemas. Introduce los conceptos de algoritmos, estructuras de control y programación estructurada en distintos lenguajes.",
    calificacion: 4.7,
  },
  1047: {
    codigo: "1047",
    titulo: "Contabilidad financiera",
    autor: "Gerardo Guajardo Cantú",
    editorial: "McGraw Hill",
    isbn: "978-6071513242",
    categoria: "110",
    imagen: "img/contabilidad_financiera.png",
    precio: 76000,
    sinopsis:
      "Obra clave en carreras de administración, contaduría y finanzas. Explica con ejemplos prácticos los principios contables y el registro de operaciones financieras.",
    calificacion: 4.8,
  },
};

localStorage.setItem("productos", JSON.stringify(productos));

